### PR TITLE
Allow some sass at rules

### PR DESCRIPTION
**Pull request by marcoambrosini**
Signed-off-by: marco <marcoambrosini@pm.me>

### CODE REVIEW

**Comment by skjnldsv** [comment]
Context?

**Comment by marcoambrosini** [comment]
Yeah, sorry :) 
It's some rules we use in talk, we got some warning from the last updates and these exclusions would fix them
for example https://github.com/nextcloud/spreed/blob/master/src/components/AvatarWrapper/AvatarWrapper.vue#L139

**Comment by skjnldsv** [comment]
We do tyhe same here and it works :thinking: 
https://github.com/nextcloud/photos/blob/68f1b8165eafd397e0e6a77b2dc53bef1eb0fe01/src/views/Timeline.vue#L318

**Comment by marcoambrosini** [comment]
No Idea why 🤔

**Comment by marcoambrosini** [comment]
We just override this in our config file till we know more then

**Pull request closed without merging**
